"""HCE calibration: does hce(state) predict solvability? (spec:
2026-07-06-hce-calibration-design.md — the chess-eval question,
measured.)

Samples states on-policy from real beam searches over mathgen
differentiation problems, probes each with fresh searches, reports
Spearman rho (hce vs nodes-to-solve) and a per-HCE-bin table. Rank
correlation because HCE only needs to ORDER states for beam pruning.

  python scripts/calibrate_hce.py --levels 1 2 3 --per-level 15 --max-states 300
"""

from __future__ import annotations

import argparse
import random
import statistics

import sympy as sp

from llmopt.mathgen.problems import _expression
from llmopt.search.derivation import State, beam_search, hce, is_solved

X = sp.Symbol("x")
SMALL_BUDGET = 40  # nodes: the binary solved-within-budget arm


def spearman(xs: list[float], ys: list[float]) -> float:
    """Spearman rank correlation, average ranks for ties. Inline to
    avoid a scipy dependency."""

    def ranks(vals: list[float]) -> list[float]:
        order = sorted(range(len(vals)), key=lambda i: vals[i])
        r = [0.0] * len(vals)
        i = 0
        while i < len(order):
            j = i
            while j + 1 < len(order) and vals[order[j + 1]] == vals[order[i]]:
                j += 1
            avg = (i + j) / 2 + 1
            for k in range(i, j + 1):
                r[order[k]] = avg
            i = j + 1
        return r

    rx, ry = ranks(xs), ranks(ys)
    mx, my = statistics.mean(rx), statistics.mean(ry)
    cov = sum((a - mx) * (b - my) for a, b in zip(rx, ry))
    vx = sum((a - mx) ** 2 for a in rx)
    vy = sum((b - my) ** 2 for b in ry)
    if vx == 0 or vy == 0:
        return float("nan")
    return cov / (vx * vy) ** 0.5


def sample_states(levels: list[int], per_level: int, max_states: int) -> list[State]:
    """On-policy: every candidate generated by real searches, deduped."""
    seen: set[str] = set()
    out: list[State] = []
    for level in levels:
        rng = random.Random(f"calibrate-hce-{level}-0")  # string seed
        for _ in range(per_level):
            trace: list[State] = []
            beam_search(sp.Derivative(_expression(rng, level), X),
                        max_plies=20, trace=trace)
            for s in trace:
                if s.key() not in seen and not is_solved(s):
                    seen.add(s.key())
                    out.append(s)
    rng = random.Random("calibrate-hce-subsample-0")
    if len(out) > max_states:
        out = rng.sample(out, max_states)
    return out


def probe(state: State) -> tuple[int | None, bool]:
    """(nodes-to-solve under generous budget or None, solved@small)."""
    generous = beam_search(state.expr, width=8, max_plies=20)
    small = beam_search(state.expr, width=8, max_plies=20,
                        max_nodes=SMALL_BUDGET)
    return (generous.nodes if generous.solved else None), small.solved


def main(levels: list[int], per_level: int, max_states: int) -> None:
    states = sample_states(levels, per_level, max_states)
    rows = []
    for s in states:
        nodes, small_ok = probe(s)
        rows.append((hce(s), nodes, small_ok))
    print(f"# HCE calibration — {len(rows)} on-policy states, "
          f"levels {levels}, small budget {SMALL_BUDGET} nodes")

    solved_rows = [(h, n) for h, n, _ in rows if n is not None]
    rho = spearman([h for h, _ in solved_rows], [n for _, n in solved_rows])
    print(f"solved under generous budget: {len(solved_rows)}/{len(rows)}")
    print(f"Spearman rho, hce vs nodes-to-solve: {rho:+.3f}  "
          f"(+1 = perfect ordering: low eval -> cheap solve)")

    # per-HCE-bin table (quintile bins over observed hce values)
    hs = sorted(h for h, _, _ in rows)
    edges = [hs[int(len(hs) * q / 5)] for q in range(1, 5)] + [float("inf")]
    print(f"{'hce bin':>16} {'n':>4} {'solve@40':>9} {'mean nodes':>11}")
    lo = float("-inf")
    for hi in edges:
        binned = [(n, ok) for h, n, ok in rows if lo < h <= hi]
        if binned:
            ns = [n for n, _ in binned if n is not None]
            mn = statistics.mean(ns) if ns else float("nan")
            rate = sum(ok for _, ok in binned) / len(binned)
            label = f"({lo:.0f}, {hi:.0f}]"
            print(f"{label:>16} {len(binned):>4} {rate:>9.2f} {mn:>11.1f}")
        lo = hi


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--levels", type=int, nargs="+", default=[1, 2, 3])
    ap.add_argument("--per-level", type=int, default=15)
    ap.add_argument("--max-states", type=int, default=300)
    a = ap.parse_args()
    main(a.levels, a.per_level, a.max_states)
