"""HCE calibration: does hce(state) predict solvability? (spec:
2026-07-06-hce-calibration-design.md — the chess-eval question,
measured.)

Samples states on-policy from real beam searches over mathgen
differentiation problems, probes each with fresh searches, reports
Spearman rho (hce vs nodes-to-solve) and a per-HCE-bin table. Rank
correlation because HCE only needs to ORDER states for beam pruning.

  python scripts/calibrate_hce.py --levels 1 2 3 --per-level 15 --max-states 300
"""

from __future__ import annotations

import argparse
import random
import signal
import statistics
import time

import sympy as sp

from llmopt.mathgen.problems import _expression
from llmopt.search.derivation import State, beam_search, hce, is_solved

X = sp.Symbol("x")
SMALL_BUDGET = 40   # nodes: the binary solved-within-budget arm
GENEROUS = 400      # nodes: cap for sampling + the nodes-to-solve arm.
# Uncapped probes explode on *failing* integration states (beam runs to
# max_plies exhaustion); 400 is where the rung-2 budget chart saturated,
# so nodes-to-solve is right-censored there and failures are reported.


def spearman(xs: list[float], ys: list[float]) -> float:
    """Spearman rank correlation, average ranks for ties. Inline to
    avoid a scipy dependency."""

    def ranks(vals: list[float]) -> list[float]:
        order = sorted(range(len(vals)), key=lambda i: vals[i])
        r = [0.0] * len(vals)
        i = 0
        while i < len(order):
            j = i
            while j + 1 < len(order) and vals[order[j + 1]] == vals[order[i]]:
                j += 1
            avg = (i + j) / 2 + 1
            for k in range(i, j + 1):
                r[order[k]] = avg
            i = j + 1
        return r

    rx, ry = ranks(xs), ranks(ys)
    mx, my = statistics.mean(rx), statistics.mean(ry)
    cov = sum((a - mx) * (b - my) for a, b in zip(rx, ry))
    vx = sum((a - mx) ** 2 for a in rx)
    vy = sum((b - my) ** 2 for b in ry)
    if vx == 0 or vy == 0:
        return float("nan")
    return cov / (vx * vy) ** 0.5


def _root(rng: random.Random, level: int, kind: str) -> sp.Expr:
    if kind == "diff":
        return sp.Derivative(_expression(rng, level), X)
    while True:
        integrand = sp.simplify(sp.diff(_expression(rng, level), X))
        if integrand != 0:
            return sp.Integral(integrand, X)


def sample_states(levels: list[int], per_level: int, max_states: int,
                  kind: str) -> list[State]:
    """On-policy: every candidate generated by real searches, deduped."""
    seen: set[str] = set()
    out: list[State] = []
    for level in levels:
        rng = random.Random(f"calibrate-hce-{kind}-{level}-0")  # string seed
        for _ in range(per_level):
            trace: list[State] = []
            beam_search(_root(rng, level, kind), max_plies=20,
                        max_nodes=GENEROUS, trace=trace)
            for s in trace:
                if s.key() not in seen and not is_solved(s):
                    seen.add(s.key())
                    out.append(s)
    rng = random.Random("calibrate-hce-subsample-0")
    if len(out) > max_states:
        out = rng.sample(out, max_states)
    return out


PROBE_TIMEOUT = 120  # s wall clock per state; sympy has pathological
# corners (simplify/trigsimp on specific exp/log/trig mixes) that no
# input-size guard predicts. Timeouts are recorded as failures and
# counted honestly in the report.


class _ProbeTimeout(BaseException):
    # BaseException so beam_search's broad `except Exception` handlers
    # (verify_edge, algebra moves) cannot swallow the alarm mid-search —
    # measured: a swallowed alarm let one probe run 2050s.
    pass


def _alarm(signum, frame):
    raise _ProbeTimeout()


def probe(state: State) -> tuple[int | None, bool, bool]:
    """(nodes-to-solve or None, solved@small, timed_out)."""
    signal.signal(signal.SIGALRM, _alarm)
    signal.alarm(PROBE_TIMEOUT)
    try:
        generous = beam_search(state.expr, width=8, max_plies=20,
                               max_nodes=GENEROUS)
        small = beam_search(state.expr, width=8, max_plies=20,
                            max_nodes=SMALL_BUDGET)
        return (generous.nodes if generous.solved else None), small.solved, False
    except _ProbeTimeout:
        return None, False, True
    finally:
        signal.alarm(0)


def main(levels: list[int], per_level: int, max_states: int,
         kind: str) -> None:
    states = sample_states(levels, per_level, max_states, kind)
    print(f"sampled {len(states)} states; probing "
          f"(failing probes cost the full {GENEROUS}-node budget)...",
          flush=True)
    rows = []
    timeouts = 0
    for i, s in enumerate(states):
        t0 = time.time()
        nodes, small_ok, timed_out = probe(s)
        timeouts += timed_out
        if time.time() - t0 > 30:
            print(f"  slow state #{i} ({time.time() - t0:.0f}s, "
                  f"timeout={timed_out}): {sp.sstr(s.expr)[:100]}", flush=True)
        rows.append((hce(s), nodes, small_ok))
        if (i + 1) % 20 == 0:
            print(f"  probed {i + 1}/{len(states)}", flush=True)
    if timeouts:
        print(f"  {timeouts} probes hit the {PROBE_TIMEOUT}s wall "
              f"(counted as failures)", flush=True)
    print(f"# HCE calibration — kind={kind}, {len(rows)} on-policy states, "
          f"levels {levels}, small budget {SMALL_BUDGET} nodes")

    solved_rows = [(h, n) for h, n, _ in rows if n is not None]
    rho = spearman([h for h, _ in solved_rows], [n for _, n in solved_rows])
    print(f"solved under generous budget: {len(solved_rows)}/{len(rows)}")
    print(f"Spearman rho, hce vs nodes-to-solve: {rho:+.3f}  "
          f"(+1 = perfect ordering: low eval -> cheap solve)")

    # per-HCE-bin table (quintile bins over observed hce values)
    hs = sorted(h for h, _, _ in rows)
    edges = [hs[int(len(hs) * q / 5)] for q in range(1, 5)] + [float("inf")]
    print(f"{'hce bin':>16} {'n':>4} {'solve@40':>9} {'mean nodes':>11}")
    lo = float("-inf")
    for hi in edges:
        binned = [(n, ok) for h, n, ok in rows if lo < h <= hi]
        if binned:
            ns = [n for n, _ in binned if n is not None]
            mn = statistics.mean(ns) if ns else float("nan")
            rate = sum(ok for _, ok in binned) / len(binned)
            label = f"({lo:.0f}, {hi:.0f}]"
            print(f"{label:>16} {len(binned):>4} {rate:>9.2f} {mn:>11.1f}")
        lo = hi


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--levels", type=int, nargs="+", default=[1, 2, 3])
    ap.add_argument("--per-level", type=int, default=15)
    ap.add_argument("--max-states", type=int, default=300)
    ap.add_argument("--kind", choices=["diff", "int"], default="diff")
    a = ap.parse_args()
    main(a.levels, a.per_level, a.max_states, a.kind)
