"""Generate adoptable read-only tables from Sol's enriched index.

Usage: .venv/bin/python scripts/sol_generate_tables.py
"""
from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

SRC = Path("docs/sol/results-index-enriched.jsonl")
OUT = Path("docs/sol/TABLES.md")


def _refs(value) -> list[str]:
    if not value:
        return []
    return [value] if isinstance(value, str) else list(value)


def _entry_row(entry: dict) -> str:
    return (f"| {entry.get('date') or 'undated'} | `{entry['id']}` | "
            f"{entry['maturity_source']} | {entry['title'].replace('|', '&#124;')} |")


def main() -> None:
    entries = [json.loads(line) for line in SRC.read_text().splitlines()]
    by_id = {e["id"]: e for e in entries}
    lines = [
        "# Generated ledger tables", "",
        "Generated by `scripts/sol_generate_tables.py`; this file is a read-only "
        "view over `docs/sol/results-index-enriched.jsonl`.", "",
    ]
    for status in ("adopted", "null", "retracted"):
        rows = [e for e in entries if e["maturity"] == status
                or status in e.get("maturity_flags", [])]
        lines += [f"## {status.title()} ({len(rows)})", "",
                  "| Date | Entry | Label source | Title |",
                  "|---|---|---|---|"]
        lines += [_entry_row(e) for e in rows]
        if not rows:
            lines.append("| — | — | — | No entries matched. |")
        lines.append("")

    edges = set()
    for e in entries:
        for target in _refs(e.get("amends")):
            if target in by_id:
                edges.add((target, e["id"], "amended by"))
        for target in _refs(e.get("superseded_by")):
            if target in by_id:
                edges.add((e["id"], target, "superseded by"))
        for target in _refs(e.get("inferred_superseded_by")):
            if target in by_id:
                edges.add((e["id"], target, "inferred heading match"))

    per_thread = defaultdict(list)
    for old, new, relation in sorted(edges):
        threads = sorted(set(by_id[old].get("threads", []))
                         | set(by_id[new].get("threads", []))) or ["unthreaded"]
        for thread in threads:
            per_thread[thread].append((old, new, relation))
    lines += ["## Per-thread lineage", "",
              "Explicit `amends`/`superseded_by` edges are shown alongside "
              "clearly labeled inferred heading matches.", ""]
    for thread in sorted(per_thread):
        lines += [f"### {thread}", "", "| Earlier | Relation | Later |",
                  "|---|---|---|"]
        for old, new, relation in per_thread[thread]:
            lines.append(f"| `{old}` | {relation} | `{new}` |")
        lines.append("")

    unresolved = [e for e in entries if e.get("replication_open")
                  and e["maturity"] not in {"retracted", "superseded"}]
    lines += [f"## Unresolved replications ({len(unresolved)})", "",
              "Only explicit n>=3 requirements or explicitly pending/unrun "
              "device legs are included; an n=1 mention alone is not enough.", "",
              "| Date | Entry | Ledger evidence |", "|---|---|---|"]
    for e in unresolved:
        evidence = e.get("replication_evidence", "").replace("|", "&#124;")
        lines.append(f"| {e.get('date') or 'undated'} | `{e['id']}` | {evidence} |")
    if not unresolved:
        lines.append("| — | — | No explicit unresolved replication fences matched. |")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"{len(entries)} entries, {len(edges)} lineage edges, "
          f"{len(unresolved)} unresolved -> {OUT}")


if __name__ == "__main__":
    main()
