"""ATOM-DIET-TRAJECTORY-1 instrument (pre-reg RESULTS L66546, sealed by
AMENDMENT -SEAL L66822): paired stock/atoms births at the matched
15,420-step horizon with snapshot emission. Sibling of the results-cited
scratch/birth19m_atoms_ladder.py (not edited): the recipe, dose
mechanics, no-op precondition and training loop are verbatim. Changes:
(i) snapshots saved at the frozen schedule (step 0, 463, then every
1,028 to 15,420); (ii) the arm's three actual token-id batch-stream
digests are asserted against the pinned values before the first
optimizer step; (iii) unique output paths under checkpoints/atomtraj1/;
(iv) non-finite loss aborts; (v) NO gate runs in this file (post-hoc
gates: scratch/birth19m_atoms_trajgate.py). Every receipt field is
derived from the artifacts this process opened or wrote.

Env: ARM=stock|atoms SEED=<int> [ORDER_INDEX=<0..5>]
     SMOKE=1        path-isolated (checkpoints/atomtraj1_smoke/,
                    logs/atomtraj1/smoke.jsonl), seed must be >= 11,
                    steps capped at SMOKE_STEPS (default 1,100),
                    optional TAG suffix on the output directory
     DRYRUN=1       stream assertions only, exit before any output
     EMIT=0         skip snapshot files (CPU emission-neutrality probe
                    only; smoke mode required)
     DEVICE=cpu     device override (probe only; smoke mode required)

Usage: ARM=stock SEED=5 ORDER_INDEX=0 .venv/bin/python scratch/birth19m_atoms_traj.py
"""
import datetime
import hashlib
import json
import os
import resource
import shutil
import subprocess
import sys
import time
from pathlib import Path

sys.path.insert(0, ".")
sys.path.insert(0, "scripts")
sys.path.insert(0, "scratch")

LADDER_ARM = os.environ.get("ARM", "")
SEED = int(os.environ["SEED"])
assert LADDER_ARM in ("stock", "atoms"), LADDER_ARM
SMOKE = os.environ.get("SMOKE") == "1"
DRYRUN = os.environ.get("DRYRUN") == "1"
EMIT = os.environ.get("EMIT", "1") != "0"
DEVICE_OVERRIDE = os.environ.get("DEVICE", "")
SMOKE_STEPS = int(os.environ.get("SMOKE_STEPS", "1100"))
TAG = os.environ.get("TAG", "")
ORDER_INDEX = os.environ.get("ORDER_INDEX", "")

DISCOVERY_SEEDS = (5, 6, 7)
RESERVED_SEEDS = (8, 9, 10)
SPENT_SEEDS = (2, 3, 4)
if SMOKE:
    assert SEED >= 11 and SEED not in DISCOVERY_SEEDS + RESERVED_SEEDS + SPENT_SEEDS, f"smoke seed {SEED} is not an excluded seed"
    assert LADDER_ARM == "stock", "qualification is stock-only"
else:
    assert SEED in DISCOVERY_SEEDS, f"registered seeds are {DISCOVERY_SEEDS}, got {SEED}"
    assert EMIT and not DEVICE_OVERRIDE and not TAG, "EMIT/DEVICE/TAG overrides are smoke-only"

os.environ["ARM"] = "off"       # frozen module import side-effects only
os.environ["BIRTH_SEED"] = str(SEED)

import torch  # noqa: E402

import birth19m_curric as C  # noqa: E402  (frozen, import-only)
import train_mathnative as TM  # noqa: E402
from tenet_d2_revdiet import gate_band_exprs, norm  # noqa: E402
from atomtraj_pins import state_digest, stream_digest, encode_flagged  # noqa: E402

EPOCHS, BS = C.EPOCHS, C.BS
SHARD = Path("data/micromodel_atoms_shard0.jsonl")
STEPS_TOTAL_PIN = 15_420
SCHEDULE = [0, 463] + list(range(1_028, STEPS_TOTAL_PIN + 1, 1_028))
ROOT = Path("checkpoints/atomtraj1_smoke" if SMOKE else "checkpoints/atomtraj1")
OUTDIR = ROOT / f"{LADDER_ARM}_s{SEED}{TAG}"
RECEIPTS = Path("logs/atomtraj1/smoke.jsonl" if SMOKE else "logs/atomtraj1/births.jsonl")
MIN_FREE_BYTES = 15 * 1024 ** 3

# Pinned actual token-id batch-stream digests (PRE-REG L66546; regenerated by
# scratch/atomtraj_pins.py from the frozen curric functions and the shard).
PINNED_STREAMS = {
    "stock": ["18a6c14a6e7cd48e871e1645bfef1f6c89297681531ee34cc48740665ea003f7",
              "a3bf1ab910faf09f1cdd1455dd54a16474eb4cf4433deb96b1e4607c7cd18324",
              "7ff1b63ea45b343a94ba2092deeaf3da4abbd006085a190f0167781f579d433b"],
    "atoms": ["29f35e9931effbdb1db45378a2be80a4b0fbe44e1d26bc1e03492faa808699e8",
              "b07e1e71ff24c90f8478f536bc95ff2b7aef2dc80761045b285b42da1032f222",
              "3fc36a33bcc257eb6941bd237d1a7ff3d0f81758add787ea7a0f2c3517779a35"],
}
PINNED_SHARD_SHA = "193ebc5d48c639afeed7f29fd87e6a1a0c9026ed35affc7aa61988f8d261b036"
PINNED_COUNTS = {"enc_stock": 164_490, "enc_atoms": 170_490, "steps_per_epoch": 5_140,
                 "stock": {"dropped": [0, 0, 0], "atom_rows": [0, 0, 0]},
                 "atoms": {"dropped": [187, 187, 187], "atom_rows": [5820, 5706, 5850]}}


def sha256_file(p):
    return hashlib.sha256(Path(p).read_bytes()).hexdigest()


def git_head():
    return subprocess.run(["git", "rev-parse", "--short", "HEAD"], capture_output=True, text=True).stdout.strip()


def git_dirty():
    return bool(subprocess.run(["git", "status", "--porcelain"], capture_output=True, text=True).stdout.strip())


def now():
    return datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds")


def save_snapshot(model, step, record):
    """Save the state dict (CPU float32) as step_{n:05d}.pt and record the
    file sha256 and canonical state_digest read back from the file."""
    p = OUTDIR / f"step_{step:05d}.pt"
    if p.exists():
        raise SystemExit(f"REFUSING: {p} exists")
    sd = {k: v.detach().to("cpu") for k, v in model.state_dict().items()}
    torch.save(sd, p)
    back = torch.load(p, map_location="cpu")
    record[str(step)] = {"file_sha256": sha256_file(p), "state_digest": state_digest(back)}


def main():
    if OUTDIR.exists() and not DRYRUN:
        raise SystemExit(f"REFUSING: {OUTDIR} exists")
    if not SHARD.exists():
        raise SystemExit("NOT-RUN: shard absent")
    shard_sha = hashlib.sha256(SHARD.read_bytes()).hexdigest()
    assert shard_sha == PINNED_SHARD_SHA, f"shard sha drift {shard_sha}"
    tok = TM.MathTokenizer()
    stock_rows = C.load_excised_rows()

    enc_stock, _ = C.encode_with_levels(stock_rows, tok)
    if LADDER_ARM == "atoms":
        atoms = [json.loads(l) for l in SHARD.open()]
        band = set(gate_band_exprs())
        atoms = [r for r in atoms
                 if norm(str(r["cur"])) not in band
                 and norm(str(r["nxt"])) not in band]
        print(f"[traj] shard {SHARD}: {len(atoms)} rows after "
              f"in-driver excision", flush=True)
        enc, is_atom = encode_flagged(stock_rows + atoms, tok)
    else:
        atoms = []
        enc, is_atom = enc_stock, [False] * len(enc_stock)
    print(f"[traj] arm={LADDER_ARM} seed={SEED}: stock "
          f"{len(enc_stock)} seq, train {len(enc)} seq "
          f"({sum(is_atom)} atoms)", flush=True)

    C.assert_noop(enc_stock)    # precondition, fresh, in-process

    steps_per_epoch = len(C.stock_epoch_stream(len(enc_stock), 0))
    steps_total = EPOCHS * (len(enc_stock) // BS)
    assert steps_total == STEPS_TOTAL_PIN, steps_total
    assert len(enc_stock) == PINNED_COUNTS["enc_stock"] and len(enc) == PINNED_COUNTS[f"enc_{LADDER_ARM}"]
    assert steps_per_epoch == PINNED_COUNTS["steps_per_epoch"]

    # stream identity: the actual token-id batches of every epoch, before any step
    streams, digests, dropped_l, atom_rows_l = [], [], [], []
    for ep in range(EPOCHS):
        stream = C.stock_epoch_stream(len(enc), ep)
        dropped = len(stream) - steps_per_epoch
        stream = stream[:steps_per_epoch]
        digests.append(stream_digest(enc, stream))
        dropped_l.append(dropped)
        atom_rows_l.append(sum(1 for a, b in stream for j in range(a, b) if is_atom[j]))
        streams.append(stream)
    for ep in range(EPOCHS):
        if digests[ep] != PINNED_STREAMS[LADDER_ARM][ep]:
            raise SystemExit(f"REFUSING: stream digest mismatch {LADDER_ARM} e{ep}: {digests[ep]}")
    assert dropped_l == PINNED_COUNTS[LADDER_ARM]["dropped"], dropped_l
    assert atom_rows_l == PINNED_COUNTS[LADDER_ARM]["atom_rows"], atom_rows_l
    print(f"[traj] stream digests verified {LADDER_ARM} e0..e2; dropped {dropped_l}; atom rows {atom_rows_l}", flush=True)
    if DRYRUN:
        print(json.dumps({"dryrun": True, "arm": LADDER_ARM, "seed": SEED, "streams": digests,
                          "dropped": dropped_l, "atom_rows": atom_rows_l, "shard_sha256": shard_sha}))
        return
    free = shutil.disk_usage(".").free
    if free < MIN_FREE_BYTES:
        raise SystemExit(f"NOT-RUN: disk free {free / 1024**3:.1f} GB < 15 GB")

    dev = DEVICE_OVERRIDE or ("mps" if torch.backends.mps.is_available() else
                              "cuda" if torch.cuda.is_available() else "cpu")
    torch.manual_seed(SEED)
    model = TM.build_model(len(tok.vocab), d=384, layers=8,
                           heads=6, ffn=1536).to(dev)
    opt = torch.optim.AdamW(model.parameters(), lr=3e-4,
                            weight_decay=0.01)
    sched = torch.optim.lr_scheduler.OneCycleLR(
        opt, max_lr=3e-4, total_steps=steps_total, pct_start=0.03)
    print(f"[traj] steps_total {steps_total} "
          f"({steps_per_epoch}/epoch)", flush=True)

    cap = min(SMOKE_STEPS, steps_total) if SMOKE else steps_total
    schedule = [s for s in SCHEDULE if s <= cap]
    if cap not in schedule:
        schedule.append(cap)
    OUTDIR.mkdir(parents=True, exist_ok=False)
    RECEIPTS.parent.mkdir(parents=True, exist_ok=True)
    snapshots = {}
    started = now()
    init_digest = state_digest(model.state_dict())
    if EMIT:
        save_snapshot(model, 0, snapshots)
        assert snapshots["0"]["state_digest"] == init_digest, "step_0 file digest v in-memory init"

    step = 0
    t0 = time.time()
    atom_exposure = []
    done = False
    for ep in range(EPOCHS):
        stream = streams[ep]
        n_atom_rows = atom_rows_l[ep]
        atom_exposure.append(n_atom_rows)
        print(f"[traj] ep{ep}: {len(stream)} batches ({dropped_l[ep]} "
              f"dropped to match stock count), {n_atom_rows} atom "
              f"rows in stream", flush=True)
        for a, b in stream:
            batch = enc[a:b]
            L = max(len(s) for s in batch)
            ids = torch.tensor([s + [tok.pad_id] * (L - len(s))
                                for s in batch], device=dev)
            mask = torch.tensor([[1] * len(s) + [0] * (L - len(s))
                                 for s in batch], device=dev)
            logits = model(ids[:, :-1], mask[:, :-1])
            labels = ids[:, 1:].clone()
            labels[mask[:, 1:] == 0] = -100
            loss = torch.nn.functional.cross_entropy(
                logits.reshape(-1, logits.shape[-1]),
                labels.reshape(-1), ignore_index=-100)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            opt.step()
            if sched.last_epoch < steps_total - 1:
                sched.step()
            opt.zero_grad()
            step += 1
            if not torch.isfinite(loss.detach()):
                raise SystemExit(f"ABORT: non-finite loss at step {step}")
            if step % 200 == 0:
                print(f"  step {step}/{steps_total} loss "
                      f"{float(loss.detach()):.3f} "
                      f"({step/(time.time()-t0):.1f} it/s)",
                      flush=True)
            if EMIT and step in schedule:
                save_snapshot(model, step, snapshots)
            if step >= cap:
                done = True
                break
        if done:
            break
    wall = time.time() - t0

    final_p = OUTDIR / "final.pt"
    if final_p.exists():
        raise SystemExit(f"REFUSING: {final_p} exists")
    sd_final = {k: v.detach().to("cpu") for k, v in model.state_dict().items()}
    torch.save(sd_final, final_p)
    final_back = torch.load(final_p, map_location="cpu")
    final_rec = {"file_sha256": sha256_file(final_p), "state_digest": state_digest(final_back)}
    if EMIT:
        last = torch.load(OUTDIR / f"step_{step:05d}.pt", map_location="cpu")
        if state_digest(last) != final_rec["state_digest"]:
            raise SystemExit("ABORT: state_digest(step_final) != state_digest(final)")
    print(f"[traj] saved {final_p} after {step} steps ({wall:.0f}s)", flush=True)

    # probe-only digests of the optimizer and RNG state (emission neutrality)
    h = hashlib.sha256()
    for k, v in sorted(((str(k), v) for k, v in opt.state_dict()["state"].items()), key=lambda kv: kv[0]):
        for name in sorted(v):
            t = v[name]
            h.update(f"{k}.{name}".encode())
            h.update(t.detach().to("cpu", torch.float32).contiguous().numpy().tobytes() if torch.is_tensor(t) else str(t).encode())
    opt_digest = h.hexdigest()
    rng_digest = hashlib.sha256(torch.get_rng_state().numpy().tobytes()).hexdigest()

    row = {"kind": "birth", "arm": LADDER_ARM, "seed": SEED, "steps": step, "steps_total": steps_total,
           "smoke": SMOKE, "emit": EMIT, "device": dev, "order_index": ORDER_INDEX, "tag": TAG,
           "started_utc": started, "ended_utc": now(), "wall_s": round(wall, 1),
           "peak_rss_bytes": resource.getrusage(resource.RUSAGE_SELF).ru_maxrss,
           "code_commit": git_head(), "tree_dirty": git_dirty(), "torch": torch.__version__,
           "shard_sha256": shard_sha, "n_atoms_shard": len(atoms), "enc_stock": len(enc_stock), "enc_train": len(enc),
           "stream_sha256": digests, "dropped_per_epoch": dropped_l, "atom_rows_per_epoch": atom_exposure,
           "schedule": schedule, "outdir": str(OUTDIR), "init_state_digest": init_digest,
           "snapshots": snapshots, "final": final_rec,
           "optimizer_state_digest": opt_digest, "torch_rng_digest": rng_digest}
    with RECEIPTS.open("a") as f:
        f.write(json.dumps(row) + "\n")
    print(f"[traj] receipt appended to {RECEIPTS} (final state_digest {final_rec['state_digest'][:16]})", flush=True)


if __name__ == "__main__":
    main()
