"""VERIFIED-ENDOGENOUS-DATA-CROSSFOSTER-1, donor-library stage (PRE-REG
VERIFIED-ENDOGENOUS-DATA-CROSSFOSTER-1-DONOR). Zero training. Builds the
two matched donor libraries D_A = G(W_A) and D_B = G(W_B) from the two
function-matched seed-2 specimens of WRITER-TRAJECTORY-CENSUS-0:
  A = forward OneCycle final, checkpoints/gallery19m_phase_s2.pt
  B = backward OneCycle final, checkpoints/gallery19m_backsched_s2.pt
(both from the seed-2 W_0; state digests asserted against
logs/writertraj0/census.json; the census receipts are the shared-W_0 and
function-band evidence and are re-read, never recomputed, here).

Root population (fresh, frozen before any donor output is read): roots
r = (level, seed) with seed = ROOT_BAND + 1000 * level + I0 + i, i <
N_PER_LEVEL[level], levels 3..7 in the atoms-shard mix (level 4 twice the others),
enumerated in a fixed order whose every prefix carries the population's
level mix (sorted by fractional progress per level; root_order), each
generated by llmopt.lab.gen._gen_isolated (make_integrate, fork-timeboxed)
into cur = "Integral(<sstr expr>, x)". A root is EXCLUDED before any
generation if norm(cur) is in the gate band (tenet_d2_revdiet.
gate_band_exprs), in the base diet's cur or nxt strings (the D2-excised
stock rows, the training data of both donors), or duplicates an earlier
root's norm(cur); generation failures (None) are excluded with a count.

Generation law, IDENTICAL for A and B: for each root, N_WAVES waves of
the standard gate sampler llmopt.lab.gate.sample_wave_lp (B = 8 samples
per wave, temperature 0.7, max_new 120, KV-cached; the same function the
gate uses), prompt "Current: <cur>\\nHints: none\\nStep: ", sampling seeds
SAMPLE_BAND + 1000 * root_index + 8 * wave + b (b < 8; the same seeds for
both donors); candidates deduplicated by whitespace-stripped text;
IDENTITY-REJECTION: a candidate whose norm equals norm(cur) is rejected
before the oracle; the exact oracle llmopt.lab.verify.verify_wave(cur,
candidates) decides PASS (ok) and SOLVED; only PASS candidates are
eligible. The donor's rows for a root are its distinct PASS candidates in
sampling order; canonical row identity = (norm(cur), norm(nxt)).

Matched-root / matched-dose retention (K frozen): a root is RETAINED
iff BOTH donors supplied >= K distinct PASS rows; each donor then
contributes exactly its first K PASS rows for that root. Roots are
processed in the fixed order until N_RETAIN roots are retained or the
population is exhausted; every processed root is accounted (retained /
excluded-band / excluded-diet / excluded-dup / gen-failed / inadequate-A /
inadequate-B / inadequate-both). D_A and D_B therefore have identical
root support and size N_RETAIN * K. If fewer than N_RETAIN roots are
retained from the whole population: DONOR-INACCESSIBLE.

Library row schema (mechanically the atoms-shard schema, so the
ATOM-DIET exposure law applies unchanged): {"cur", "nxt", "level",
"rule": "donor", "source": "donor-A" | "donor-B", "root_index",
"root_seed", "sample_seed", "wave", "solved"}; the recipient driver
encodes cur / nxt / level only.

Descriptive readouts (never alter K, dose, generator or the factorial):
verified yield per donor (PASS rows / samples), adequacy per donor,
retained-root count and level mix, exact and canonical overlap between
D_A and D_B (rows with equal (norm(cur), norm(nxt))), novelty v the base
diet (rows whose canonical nxt is any diet cur / nxt string), solved
fraction, nxt token-length distribution, and the cross-model teacher-
forced CE of each library under each donor (A on D_A, A on D_B, B on
D_A, B on D_B; eligible label positions, the trainer's encoding).

Outputs: data/crossfoster1/D_A.jsonl, data/crossfoster1/D_B.jsonl
(refuse-if-exists), logs/crossfoster1/donor.json (accounting, readouts,
digests of both libraries), logs/crossfoster1/donor.jsonl. SMOKE=1:
population 20 roots (4 per level), N_RETAIN 4, N_WAVES 1, outputs under
data/crossfoster1_smoke<SMOKE_TAG>/ and logs/crossfoster1/smoke<SMOKE_TAG>.jsonl.
Usage: .venv/bin/python scratch/crossfoster_donor.py
"""
import collections
import datetime
import hashlib
import json
import os
import subprocess
import sys
import time
from pathlib import Path

sys.path.insert(0, ".")
sys.path.insert(0, "scripts")
sys.path.insert(0, "scratch")
os.environ.setdefault("ARM", "off")
os.environ.setdefault("BIRTH_SEED", "0")

import sympy as sp  # noqa: E402
import torch  # noqa: E402

import birth19m_curric as C  # noqa: E402
import train_mathnative as TM  # noqa: E402
from atomtraj_pins import state_digest  # noqa: E402
from llmopt.lab.gate import sample_wave_lp  # noqa: E402
from llmopt.lab.gen import _gen_isolated  # noqa: E402
from llmopt.lab.verify import verify_wave  # noqa: E402
from tenet_d2_revdiet import gate_band_exprs, norm  # noqa: E402

SMOKE = os.environ.get("SMOKE", "0") == "1"
SMOKE_TAG = os.environ.get("SMOKE_TAG", "")
assert not SMOKE_TAG or SMOKE, "SMOKE_TAG is smoke-only"
DONORS = {"A": "checkpoints/gallery19m_phase_s2.pt", "B": "checkpoints/gallery19m_backsched_s2.pt"}
DONOR_DIGEST_PREFIX = {"A": "4633efe5d376f911", "B": "4beeedec5f9f5e91"}     # sealed (WRITER-TRAJECTORY-CENSUS-0 specimens)
W0_DIGEST_PREFIX = "eb4b0bb427f86972"                                         # the shared seed-2 W_0 (census)
CENSUS = Path("logs/writertraj0/census.json")
LEVELS = [3, 4, 5, 6, 7]
N_PER_LEVEL = {lv: int(os.environ.get("SMOKE_PER_LEVEL", "4")) for lv in [3, 4, 5, 6, 7]} if SMOKE else {3: 3600, 4: 9600, 5: 3600, 6: 3600, 7: 3600}   # registered population 24,000: the atoms-shard level mix (2400 / 900 x 4) x 4
N_RETAIN = int(os.environ.get("SMOKE_RETAIN", "4")) if SMOKE else 6000            # x K = the atoms-shard dose (6,000 rows)
K = 1                           # K 2 was inaccessible on the calibration smoke (3 of 75 roots both-adequate)
OVERLAP_DEGENERATE = 0.9        # canonical overlap of D_A and D_B at or above this: DONOR-HISTORIES-DEGENERATE
N_WAVES = int(os.environ.get("SMOKE_WAVES", "1")) if SMOKE else 4
WAVE = 8
ROOT_BAND = 8_900_000 if SMOKE else 8_800_000     # smoke roots live in their own band; the registered band starts at I0
SAMPLE_BAND = 7_900_000 if SMOKE else 40_000_000   # registered sample seeds 40.0M .. 64.0M: disjoint from every smoke band
I0 = 0 if SMOKE else 10        # registered i starts at 10: i < 4 of the 8.8M band were touched by the first (pre-band-split) smoke and are excluded
OUT_DATA = Path(f"data/crossfoster1_smoke{SMOKE_TAG}" if SMOKE else "data/crossfoster1")
OUT_LOG = Path("logs/crossfoster1")
OUT = OUT_LOG / (f"smoke{SMOKE_TAG}.jsonl" if SMOKE else "donor.json")
LOG_EVERY = 5 if SMOKE else 200


def adjudicate_size(retained):
    return "DONOR-ACCESSIBLE" if retained >= N_RETAIN else "DONOR-INACCESSIBLE"


def adjudicate(retained, overlap_rows, n_rows):
    """Pure stage law: DONOR-INACCESSIBLE if fewer than N_RETAIN roots are
    retained; else DONOR-HISTORIES-DEGENERATE if the canonical overlap of
    D_A and D_B (rows with equal (norm(cur), norm(nxt))) is >=
    OVERLAP_DEGENERATE of the library size; else DONOR-ACCESSIBLE."""
    if retained < N_RETAIN:
        return "DONOR-INACCESSIBLE"
    if n_rows > 0 and overlap_rows / n_rows >= OVERLAP_DEGENERATE:
        return "DONOR-HISTORIES-DEGENERATE"
    return "DONOR-ACCESSIBLE"


def sha256_file(p):
    return hashlib.sha256(Path(p).read_bytes()).hexdigest()


def root_order():
    """Fixed order in which EVERY prefix carries the population's level
    mix: roots sorted by fractional progress (i + 0.5) / N_PER_LEVEL[level], ties
    by level then i (so level 4, with 2.67x the others, appears 2.67x as
    often in any prefix). Deterministic; a permutation of the grid."""
    roots = [(lv, i) for lv in LEVELS for i in range(N_PER_LEVEL[lv])]
    return sorted(roots, key=lambda r: ((r[1] + 0.5) / N_PER_LEVEL[r[0]], r[0], r[1]))


def load_donor(name, tok, dev):
    p = DONORS[name]
    sd = torch.load(p, map_location="cpu")
    dg = state_digest(sd)
    m = TM.build_model(len(tok.vocab), d=384, layers=8, heads=6, ffn=1536)
    m.load_state_dict(sd)
    return m.to(dev).eval(), {"path": p, "file_sha256": sha256_file(p), "state_digest": dg}


def generate_for_root(model, tok, dev, cur, root_index):
    """All distinct PASS candidates of one donor for one root, in sampling
    order, with the identity rejection applied before the oracle."""
    prompt = tok.encode(f"Current: {cur}\nHints: none\nStep: ")
    cur_norm = norm(cur)
    rows, seen, n_samples, n_distinct, n_identity = [], set(), 0, 0, 0
    with torch.no_grad():
        for w in range(N_WAVES):
            seeds = [SAMPLE_BAND + 1000 * root_index + WAVE * w + b for b in range(WAVE)]
            texts, _, _ = sample_wave_lp(model, tok, prompt, seeds, dev)
            n_samples += len(texts)
            cands, cand_seed = [], {}
            for t, s in zip(texts, seeds):
                key = t.replace(" ", "")
                if not t or key in seen:
                    continue
                seen.add(key)
                n_distinct += 1
                if norm(t) == cur_norm:
                    n_identity += 1
                    continue
                cands.append(t)
                cand_seed[t] = (s, w)
            wv = verify_wave(cur, cands) if cands else {}
            for t in cands:
                ok, solved = wv.get(t, (False, False))
                if ok:
                    rows.append({"nxt": t, "sample_seed": cand_seed[t][0], "wave": cand_seed[t][1], "solved": bool(solved)})
    return rows, {"samples": n_samples, "distinct": n_distinct, "identity_rejected": n_identity, "pass": len(rows)}


def teacher_forced_ce(model, tok, rows, dev):
    """Mean CE over eligible label positions of the trainer's encoding of
    the rows (batches of 32, length-sorted), on the given model."""
    enc, _ = C.encode_with_levels(rows, tok)
    tot, n = 0.0, 0
    with torch.no_grad():
        for i in range(0, len(enc), 32):
            batch = enc[i:i + 32]
            L = max(len(s) for s in batch)
            ids = torch.tensor([s + [tok.pad_id] * (L - len(s)) for s in batch], device=dev)
            mask = torch.tensor([[1] * len(s) + [0] * (L - len(s)) for s in batch], device=dev)
            labels = ids[:, 1:].clone()
            labels[mask[:, 1:] == 0] = -100
            logits = model(ids[:, :-1], mask[:, :-1])
            ce = torch.nn.functional.cross_entropy(logits.reshape(-1, logits.shape[-1]), labels.reshape(-1), ignore_index=-100, reduction="sum")
            tot += float(ce)
            n += int((labels != -100).sum())
    return tot / max(n, 1), n


def main():
    OUT_LOG.mkdir(parents=True, exist_ok=True)
    if OUT.exists():
        raise SystemExit(f"REFUSING: {OUT} exists")
    if OUT_DATA.exists():
        raise SystemExit(f"REFUSING: {OUT_DATA} exists")
    commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"], capture_output=True, text=True).stdout.strip()
    dirty = bool(subprocess.run(["git", "status", "--porcelain"], capture_output=True, text=True).stdout.strip())
    if not SMOKE and dirty:
        raise SystemExit("REFUSING: registered donor stage on a dirty tree")
    dev = "mps" if torch.backends.mps.is_available() else "cpu"
    tok = TM.MathTokenizer()
    assert len(tok.vocab) == 40 and not os.environ.get("VOCAB_EXTRA")
    census = json.loads(CENSUS.read_text())
    donors, drec = {}, {}
    for name in ("A", "B"):
        donors[name], drec[name] = load_donor(name, tok, dev)
        assert drec[name]["state_digest"].startswith(DONOR_DIGEST_PREFIX[name]), f"donor {name}: state digest {drec[name]['state_digest'][:16]} v sealed {DONOR_DIGEST_PREFIX[name]}"
    # the census's specimen paths must be these files; its W_0 law is the shared-W_0 evidence
    assert census["artifacts"]["A_paths"]["15420"] == DONORS["A"] and census["artifacts"]["B_paths"]["15420"] == DONORS["B"], "donor paths v census"
    w0_digest = census["w0_seed2_state_digest"]
    assert w0_digest.startswith(W0_DIGEST_PREFIX), "census W_0 digest v sealed"
    # exclusion sets
    stock_rows = C.load_excised_rows()
    diet_norms = set()
    for r in stock_rows:
        diet_norms.add(norm(str(r["cur"])))
        diet_norms.add(norm(str(r["nxt"])))
    band = set(gate_band_exprs())
    rec = {"prereg": "VERIFIED-ENDOGENOUS-DATA-CROSSFOSTER-1", "stage": "donor", "kind": "crossfoster_donor", "smoke": SMOKE, "commit": commit, "tree_dirty": dirty,
           "source_sha256": sha256_file(__file__), "device": dev, "torch_version": torch.__version__, "donors": drec, "w0_seed2_state_digest_from_census": w0_digest,
           "census_sha256": sha256_file(CENSUS), "levels": LEVELS, "n_per_level": N_PER_LEVEL, "n_retain": N_RETAIN, "K": K, "n_waves": N_WAVES, "wave": WAVE,
           "root_band": ROOT_BAND, "i0": I0, "sample_band": SAMPLE_BAND, "overlap_degenerate": OVERLAP_DEGENERATE, "temperature": 0.7, "max_new": 120, "n_diet_rows": len(stock_rows), "n_diet_norms": len(diet_norms), "n_band_exprs": len(band),
           "started_utc": datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds")}
    order = root_order()
    acc = collections.Counter()
    libs = {"A": [], "B": []}
    union = {"A": set(), "B": set()}        # descriptive: ALL distinct PASS rows per donor on the retained roots (unmatched dose)
    stats = {"A": collections.Counter(), "B": collections.Counter()}
    seen_roots = set()
    retained, processed = 0, 0
    root_log = []
    t0 = time.time()
    for root_index, (lv, i) in enumerate(order):
        if retained >= N_RETAIN:
            break
        processed += 1
        seed = ROOT_BAND + 1000 * lv + I0 + i
        p = _gen_isolated(lv, seed)
        if p is None:
            acc["gen_failed"] += 1
            continue
        cur = f"Integral({sp.sstr(p._expr)}, x)"
        cn = norm(cur)
        if cn in band:
            acc["excluded_band"] += 1
            continue
        if cn in diet_norms:
            acc["excluded_diet"] += 1
            continue
        if cn in seen_roots:
            acc["excluded_dup"] += 1
            continue
        seen_roots.add(cn)
        out = {}
        for name in ("A", "B"):
            rows, st = generate_for_root(donors[name], tok, dev, cur, root_index)
            out[name] = rows
            for k, v in st.items():
                stats[name][k] += v
        okA, okB = len(out["A"]) >= K, len(out["B"]) >= K
        entry = {"root_index": root_index, "level": lv, "root_seed": seed, "cur": cur, "pass_A": len(out["A"]), "pass_B": len(out["B"])}
        if okA and okB:
            retained += 1
            acc["retained"] += 1
            entry["retained"] = True
            for name in ("A", "B"):
                for r in out[name]:
                    union[name].add((cn, norm(r["nxt"])))
            for name in ("A", "B"):
                for r in out[name][:K]:
                    libs[name].append({"cur": cur, "nxt": r["nxt"], "level": lv, "rule": "donor", "source": f"donor-{name}", "root_index": root_index, "root_seed": seed,
                                       "sample_seed": r["sample_seed"], "wave": r["wave"], "solved": r["solved"]})
        else:
            acc["inadequate_both" if not (okA or okB) else ("inadequate_A" if not okA else "inadequate_B")] += 1
            entry["retained"] = False
        root_log.append(entry)
        if processed % LOG_EVERY == 0:
            print(f"[donor] processed {processed} retained {retained} / {N_RETAIN} acc {dict(acc)} ({time.time() - t0:.0f}s)", flush=True)
    rec.update({"processed_roots": processed, "population": len(order), "retained_roots": retained, "accounting": dict(acc), "sampling_stats": {k: dict(v) for k, v in stats.items()},
                "root_log": root_log, "wall_s": round(time.time() - t0, 1)})
    rec["status"] = adjudicate_size(retained)
    # write libraries (also on INACCESSIBLE, for the record; the recipient rung reads only ACCESSIBLE libraries)
    OUT_DATA.mkdir(parents=True, exist_ok=False)
    for name in ("A", "B"):
        pth = OUT_DATA / f"D_{name}.jsonl"
        with pth.open("w") as f:
            for r in libs[name]:
                f.write(json.dumps(r) + "\n")
        rec[f"D_{name}"] = {"path": str(pth), "rows": len(libs[name]), "file_sha256": sha256_file(pth)}
    # descriptive readouts
    keyA = {(norm(r["cur"]), norm(r["nxt"])) for r in libs["A"]}
    keyB = {(norm(r["cur"]), norm(r["nxt"])) for r in libs["B"]}
    exactA = {(r["cur"], r["nxt"]) for r in libs["A"]}
    exactB = {(r["cur"], r["nxt"]) for r in libs["B"]}
    rd = {"canonical_overlap_rows": len(keyA & keyB), "exact_overlap_rows": len(exactA & exactB), "unique_canonical_A": len(keyA), "unique_canonical_B": len(keyB),
          "level_mix_retained": dict(collections.Counter(r["level"] for r in libs["A"])),
          "solved_frac": {n: (sum(r["solved"] for r in libs[n]) / max(1, len(libs[n]))) for n in ("A", "B")},
          "nxt_in_diet_norms": {n: sum(norm(r["nxt"]) in diet_norms for r in libs[n]) for n in ("A", "B")},
          "nxt_token_len_median": {n: (sorted(len(tok.encode(r["nxt"])) for r in libs[n])[len(libs[n]) // 2] if libs[n] else None) for n in ("A", "B")},
          "union_rows": {n: len(union[n]) for n in ("A", "B")}, "union_canonical_overlap_rows": len(union["A"] & union["B"]),
          "roots_with_any_donor_specific_row": len({k[0] for k in (union["A"] ^ union["B"])}),
          "yield_pass_per_sample": {n: (stats[n]["pass"] / max(1, stats[n]["samples"])) for n in ("A", "B")},
          "adequacy": {"A": (acc["retained"] + acc["inadequate_B"]) / max(1, acc["retained"] + acc["inadequate_A"] + acc["inadequate_B"] + acc["inadequate_both"]),
                       "B": (acc["retained"] + acc["inadequate_A"]) / max(1, acc["retained"] + acc["inadequate_A"] + acc["inadequate_B"] + acc["inadequate_both"])}}
    if libs["A"] and libs["B"]:
        rd["teacher_forced_ce"] = {f"{m}_on_D_{n}": teacher_forced_ce(donors[m], tok, libs[n], dev)[0] for m in ("A", "B") for n in ("A", "B")}
    rec["readouts"] = rd
    rec["status"] = adjudicate(retained, rd["canonical_overlap_rows"], len(libs["A"]))
    rec["ended_utc"] = datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds")
    if SMOKE:
        with OUT.open("a") as f:
            f.write(json.dumps(rec) + "\n")
        print(f"[donor] smoke row appended: {rec['status']} retained {retained} readouts {json.dumps(rd)[:300]}")
    else:
        OUT.write_text(json.dumps(rec, indent=1))
        with (OUT_LOG / "donor.jsonl").open("a") as f:
            f.write(json.dumps({k: v for k, v in rec.items() if k != "root_log"}) + "\n")
        print(f"[donor] written {OUT}: {rec['status']} retained {retained} of {processed} processed; D_A {rec['D_A']['rows']} rows, D_B {rec['D_B']['rows']} rows")


if __name__ == "__main__":
    main()
