"""MATH-CYBER-1 AX-FIXTURE-0 — the frozen ActionProgram
interchange fixture for Axiom Tranche A
(AX-MATHCYBER-ACTIONPROGRAM-FIXTURE-0).

Emits, under logs/mathworld1/axfixture/ (refuse-if-exists):
- parents.jsonl: every parent of the frozen 101-decision corpus —
  fixture_id, episode_id/step_id, parent_id (srepr sha16),
  state_srepr (authoritative interchange), state_sstr
  (model-facing print), state_visible_v1 (the original v1 visible
  string, evidence binding), n_legal (complete legal-set
  cardinality), visible_match flag (sstr == v1 string; a
  MEASUREMENT, never normalized).
- actions.jsonl: all 725 legal actions under the canonical
  ACTION-FINAL schema — rule, site_kind (W|D|I|L), site_ordinal
  (first-preorder unique-site law; -1 for whole-expression),
  param_kind (none|u_choice|term_index), param_index (-1 for
  none), program_text (ActionGCTok serialization, diagnostic
  only — structured fields are the semantic identity), child_sstr,
  child_srepr, child_hash, rule_target (historical provenance).
- unprod_stress.jsonl: all 2,894 PDC-matched unique i_unprod
  edges (term_index stress stratum, SEPARATE replay denominator) —
  cur_sha, cur (visible string domain, the PDC law), site_ordinal,
  term_index, program_text, child_sstr.
- axfixture_manifest.json: counts, per-file sha256, producer file
  shas (start_provenance), bar booleans.

Semantic parameter fields are GENERATED by rule semantics only
(iparts_children u_choice map; trace_unprod term map; deterministic
single-accepted-child assert) — never by child-key/hash-sorted
selection. Replay self-bars re-decode every row from the
structured fields alone before the fixture is considered emitted.

Zero model, zero training, zero fresh seeds, zero search, zero
Axiom mutation.

    .venv/bin/python scratch/mathworld1_axfixture.py        (Mac)
"""
import glob
import hashlib
import json
import multiprocessing as mp
import sys
from collections import Counter, defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import sympy as sp  # noqa: E402

import llmopt.search.derivation as derivation  # noqa: E402
from llmopt.lab.provenance import (completion_commit,  # noqa: E402
                                   start_provenance)
from llmopt.search.derivation import State, successors  # noqa: E402
from scratch.mathworld1_actionsem import (RULE_KIND,  # noqa: E402
                                          apply_at, iparts_children,
                                          sites_preorder)
from scratch.mathworld1_actionfinal import (  # noqa: E402
    unprod_term_children)
from scratch.mathworld1_actiontok import ActionGCTok  # noqa: E402
from scratch.mathworld1_srepr_export import srepr_inverse  # noqa: E402

OUTDIR = Path("logs/mathworld1/axfixture")


def sha(t: str) -> str:
    return hashlib.sha256(t.encode()).hexdigest()[:16]


def fsha(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def serialize(rule, kind, ordinal, pkind, pindex):
    op = f"<r:{rule}>"
    if kind is None:
        return f"{op}\n"
    if pkind == "u_choice":
        return f"{op} {kind}{ordinal} u{pindex}\n"
    if pkind == "term_index":
        return f"{op} {kind}{ordinal} t{pindex}\n"
    return f"{op} {kind}{ordinal}\n"


def build_core(tok):
    states = {}
    for l in open("logs/mathworld1/states_srepr.jsonl"):
        r = json.loads(l)
        states[(r["episode_id"], r["step_id"])] = r
    v1 = {}
    for l in open("logs/mathworld1/states.jsonl"):
        r = json.loads(l)
        v1[(r["episode_id"], r["step_id"])] = r
    acts = defaultdict(list)
    for l in open("logs/mathworld1/actions_srepr.jsonl"):
        r = json.loads(l)
        acts[(r["episode_id"], r["step_id"])].append(r)

    parents_rows, action_rows = [], []
    c = Counter()
    for fid, key in enumerate(sorted(acts)):
        srow = states[key]
        parent = srepr_inverse(srow["state_before"])
        pkey = sp.srepr(parent)
        if sha(pkey) != srow["state_before_hash"]:
            raise SystemExit(f"BINDING state_hash {key}")
        derivation._RULE_CACHE.clear()
        gen = sorted(successors(State(parent)),
                     key=lambda nc: (nc[0], nc[1].key()))
        if (Counter(sha(x.key()) for _, x in gen)
                != Counter(a["child_hash"] for a in acts[key])):
            raise SystemExit(f"BINDING legal_set {key}")
        accepted = defaultdict(set)
        child_srepr_of = {}
        for name, ch in gen:
            rule = name.split("@", 1)[0] if "@" in name else name
            accepted[rule].add(ch.key())
            child_srepr_of[sha(ch.key())] = ch.key()
        psstr = sp.sstr(parent)
        parents_rows.append({
            "fixture_id": f"P{fid:04d}",
            "episode_id": key[0], "step_id": key[1],
            "parent_id": srow["state_before_hash"],
            "state_srepr": srow["state_before"],
            "state_sstr": psstr,
            "state_visible_v1": v1[key]["state_before"],
            "visible_match": psstr == v1[key]["state_before"],
            "n_legal": len(acts[key])})
        seen_programs = {}
        for a in acts[key]:
            rule = a["rule"]
            kind = RULE_KIND[rule]
            if kind is None:
                site, node = -1, None
            else:
                hits = []
                for i, cand in enumerate(
                        sites_preorder(parent, kind)):
                    ck, _ = apply_at(parent, rule, cand)
                    if any(sha(k) == a["child_hash"]
                           for k in set(ck) & accepted[rule]):
                        hits.append((i, cand))
                if not hits:
                    raise SystemExit(f"UNADDRESSABLE {key} {rule}")
                site, node = hits[0]
            if rule == "i_parts":
                uc_map, _ = iparts_children(parent, node)
                m = [u for u, k in uc_map.items()
                     if sha(k) == a["child_hash"]]
                if len(m) != 1:
                    raise SystemExit(f"U-AMBIG {key}")
                pkind, pindex = "u_choice", m[0]
            elif rule == "i_unprod":
                tmap, parity = unprod_term_children(parent, node)
                if not parity:
                    raise SystemExit(f"PARITY {key}")
                m = [t for t, ks in tmap.items()
                     if any(sha(k) == a["child_hash"]
                            for k in ks & accepted[rule])]
                if len(m) != 1:
                    raise SystemExit(f"T-AMBIG {key}")
                pkind, pindex = "term_index", m[0]
            else:
                if kind is None:
                    dset = accepted[rule]
                else:
                    ck, _ = apply_at(parent, rule, node)
                    dset = set(ck) & accepted[rule]
                if len(dset) != 1:
                    raise SystemExit(f"DET-AMBIG {key} {rule}")
                pkind, pindex = "none", -1
            program = (rule, site, pkind, pindex)
            child_srepr = child_srepr_of[a["child_hash"]]
            if program in seen_programs \
                    and seen_programs[program] != a["child_hash"]:
                c["collision"] += 1
            seen_programs[program] = a["child_hash"]
            text = serialize(rule, kind, site, pkind, pindex)
            ids = tok.encode(text)
            if tok.decode(ids) != text \
                    or tok.res_id[f"<r:{rule}>"] not in ids:
                raise SystemExit(f"TOK {key} {rule}")
            action_rows.append({
                "fixture_id": f"A{len(action_rows):04d}",
                "episode_id": key[0], "step_id": key[1],
                "parent_id": srow["state_before_hash"],
                "rule": rule,
                "site_kind": kind if kind else "W",
                "site_ordinal": site,
                "param_kind": pkind,
                "param_index": pindex,
                "program_text": text,
                "child_sstr": sp.sstr(srepr_inverse(child_srepr)),
                "child_srepr": child_srepr,
                "child_hash": a["child_hash"],
                "rule_target": a.get("rule_target")})
            c["emitted"] += 1
    return parents_rows, action_rows, c


def replay_core(parents_rows, action_rows):
    """Decode every action row from STRUCTURED FIELDS ALONE."""
    par = {p["parent_id"]: p for p in parents_rows}
    by_parent = defaultdict(list)
    for a in action_rows:
        by_parent[a["parent_id"]].append(a)
    ok = fail = 0
    for pid, rows in by_parent.items():
        parent = srepr_inverse(par[pid]["state_srepr"])
        derivation._RULE_CACHE.clear()
        gen = list(successors(State(parent)))
        accepted = defaultdict(set)
        for name, ch in gen:
            rule = name.split("@", 1)[0] if "@" in name else name
            accepted[rule].add(ch.key())
        for a in rows:
            rule, site = a["rule"], a["site_ordinal"]
            node = (None if a["site_kind"] == "W" else
                    sites_preorder(parent, a["site_kind"])[site])
            if a["param_kind"] == "u_choice":
                dk = iparts_children(parent, node)[0].get(
                    a["param_index"])
                dec = {dk} if dk else set()
            elif a["param_kind"] == "term_index":
                tmap, parity = unprod_term_children(parent, node)
                dec = (tmap.get(a["param_index"], set())
                       & accepted[rule]) if parity else set()
            else:
                dset = (accepted[rule] if node is None else
                        set(apply_at(parent, rule, node)[0])
                        & accepted[rule])
                dec = dset if len(dset) == 1 else set()
            if len(dec) == 1 and sha(next(iter(dec))) \
                    == a["child_hash"]:
                ok += 1
            else:
                fail += 1
    return ok, fail


def load_stress_population():
    recov = defaultdict(list)
    for l in open("logs/mathworld1/pdc_relabel.jsonl"):
        r = json.loads(l)
        for nxt, cl in r.get("rows", {}).items():
            if (isinstance(cl, dict)
                    and cl.get("class") == "unique_program"
                    and cl.get("rule") == "i_unprod"):
                recov[r["cur_sha"]].append(nxt)
    files = sorted(glob.glob("data/micromodel_chains_shard*.jsonl"))
    files.append("data/step_chains.jsonl")
    cur_of = {}
    for f in files:
        for l in open(f):
            s = json.loads(l)["cur"]
            h = sha(s)
            if h in recov and h not in cur_of:
                cur_of[h] = s
    n_edges = sum(len(v) for v in recov.values())
    if len(recov) != 2888 or n_edges != 2894:
        raise SystemExit("POPULATION MISMATCH")
    return [(h, cur_of[h], sorted(recov[h])) for h in sorted(recov)]


def stress_work(item):
    """Emit + replay stress rows for one parent. Returns rows,
    fail count, skip counter (multi-limit/definite sites)."""
    cur_sha, cur, nxts = item
    parent = sp.sympify(cur)
    sites = sites_preorder(parent, "I")
    rows, whys = [], []
    remaining = list(nxts)
    for ordinal, node in enumerate(sites):
        if len(node.limits) > 1 or len(node.limits[0]) > 1:
            whys.append("site_skip_nested_or_definite")
            continue
        tmap, parity = unprod_term_children(parent, node)
        if not parity:
            whys.append("site_skip_parity")
            continue
        vis = {t: {sp.sstr(srepr_inverse(k)) for k in ks}
               for t, ks in tmap.items()}
        for nxt in list(remaining):
            terms = [t for t, vs in vis.items() if nxt in vs]
            if not terms:
                continue
            if len(terms) != 1 or vis[terms[0]] != {nxt}:
                whys.append("replay_fail")
                remaining.remove(nxt)
                continue
            t = terms[0]
            rows.append({
                "cur_sha": cur_sha, "cur": cur,
                "rule": "i_unprod", "site_kind": "I",
                "site_ordinal": ordinal,
                "param_kind": "term_index", "param_index": t,
                "program_text": serialize(
                    "i_unprod", "I", ordinal, "term_index", t),
                "child_sstr": nxt})
            remaining.remove(nxt)
    for _ in remaining:
        whys.append("unaddressable")
    return rows, whys


def main():
    if OUTDIR.exists():
        raise SystemExit(f"REFUSING: {OUTDIR} exists")
    START = start_provenance(
        ["scratch/mathworld1_axfixture.py",
         "scratch/mathworld1_actionfinal.py",
         "scratch/mathworld1_unprodsem.py",
         "scratch/mathworld1_actionsem.py",
         "scratch/mathworld1_actiontok.py",
         "scratch/mathworld1_srepr_export.py",
         "llmopt/search/derivation.py", "llmopt/search/rules.py"])
    tok = ActionGCTok()
    parents_rows, action_rows, c = build_core(tok)
    print(f"[axfix] core emitted: parents={len(parents_rows)} "
          f"actions={len(action_rows)}", flush=True)
    core_ok, core_fail = replay_core(parents_rows, action_rows)
    print(f"[axfix] core replay: ok={core_ok} fail={core_fail}",
          flush=True)

    items = load_stress_population()
    ctx = mp.get_context("fork")
    stress_rows, why = [], Counter()
    with ctx.Pool(9) as pool:
        for rows, whys in pool.imap(stress_work, items,
                                    chunksize=8):
            stress_rows.extend(rows)
            for w in whys:
                why[w] += 1
    # program_text round-trip on every stress row
    tok_fail = sum(
        1 for r in stress_rows
        if tok.decode(tok.encode(r["program_text"]))
        != r["program_text"])
    print(f"[axfix] stress rows={len(stress_rows)} "
          f"whys={dict(why)} tok_fail={tok_fail}", flush=True)

    OUTDIR.mkdir(parents=True)
    for name, rows in [("parents.jsonl", parents_rows),
                       ("actions.jsonl", action_rows),
                       ("unprod_stress.jsonl", stress_rows)]:
        with open(OUTDIR / name, "w") as f:
            for r in rows:
                f.write(json.dumps(r) + "\n")
    replay_fails = why.get("replay_fail", 0) \
        + why.get("unaddressable", 0)
    manifest = {
        "core": {"parents": len(parents_rows),
                 "actions": len(action_rows),
                 "collisions": c.get("collision", 0),
                 "replay_ok": core_ok, "replay_fail": core_fail,
                 "visible_match": sum(
                     p["visible_match"] for p in parents_rows)},
        "stress": {"rows": len(stress_rows),
                   "replay_fail": replay_fails,
                   "whys": dict(why), "tok_roundtrip_fail": tok_fail,
                   "denominator_note":
                       "separate from core full-legal-set"},
        "files": {n: fsha(OUTDIR / n) for n in
                  ("parents.jsonl", "actions.jsonl",
                   "unprod_stress.jsonl")},
        "bars": {
            "CORE_COUNTS": len(parents_rows) == 101
                and len(action_rows) == 725,
            "CORE_NO_COLLISION": c.get("collision", 0) == 0,
            "CORE_REPLAY": core_ok == 725 and core_fail == 0,
            "STRESS_REPLAY": len(stress_rows) == 2894
                and replay_fails == 0,
            "TOK_ROUNDTRIP": tok_fail == 0,
        },
        "start": START, "completion_commit": completion_commit()}
    (OUTDIR / "axfixture_manifest.json").write_text(
        json.dumps(manifest, indent=1))
    print(json.dumps({k: v for k, v in manifest.items()
                      if k != "start"}, indent=1), flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
